version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/data/pipelines"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["security", "dependencies"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["security", "dependencies"]

