version: 1
cycle_id: 2025-09-02
snapshot_rev: git:abcdef1234
owners:
  - team: web-frontend
    lead: alice@example.com
backlog:
  - id: FE-CRIT-001
    title: Checkout - Address Validation UX
    priority: P0
    effort_points: 5
    owner: alice
    tags: [critical_path, PII]
    dependencies: [BE-CRIT-001]
    acceptance_criteria:
      - Invalid addresses prompt corrections with inline hints
      - Validation errors logged without PII
  - id: FE-CRIT-002
    title: Checkout - Payment Method Selector Accessibility
    priority: P0
    effort_points: 3
    owner: bob
    tags: [critical_path, a11y]
    dependencies: []
    acceptance_criteria:
      - Keyboard-only navigation supported
      - Screen readers announce selection state
  - id: FE-102
    title: Order History - Pagination
    priority: P1
    effort_points: 3
    owner: carol
    tags: [feature]
    dependencies: [BE-201]
    acceptance_criteria:
      - Lazy load next page on scroll end