name: Security Framework Checks

on:
  pull_request:
    paths:
      - 'frameworks/security/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema PyYAML

      - name: Run validations
        run: |
          python frameworks/security/bin/security_framework.py validate --cycle 2025-09

      - name: Generate manifest (dry run)
        run: |
          python frameworks/security/bin/security_framework.py generate-manifest --cycle 2025-09 --snapshot "git:${{ github.sha }}" --rulebook-hash sha256:rulebookhashhere

      - name: Generate digest (dry run)
        run: |
          python frameworks/security/bin/security_framework.py generate-digest --date $(date +%F) --cycle 2025-09 --snapshot "git:${{ github.sha }}" --rulebook-hash sha256:rulebookhashhere