version: 1
cycle_id: "2025-09-02"
snapshot_rev: "git:abcdef1234"
owners:
  - fe-planning@company
governance:
  fields: [version, cycle_id, snapshot_rev, owners, backlog]
  tags: [planning, fe]
backlog:
  - id: FE-2025-09-01
    title: "Address validation UI improvements"
    story_ref: "QA-API-ADDR-VAL-001"
