manifest_version: 1
cycle_id: "2025-09-02"
snapshot_rev: "git:abcdef1234"
rulebook_hash: "sha256:rulebookhashhere"
governance:
  tags: [planning, be, release]
  fields:
    owner: "be-planning@company"
    risk: "low"
    compliance: ["none"]
sealed: true
artifacts:
  - path: frameworks/planning-be/backlog/2025-09-02-be_backlog.yaml
    sha256: a83981fee5d9d13e67322a13e4754fe8bf5626a75a38767ccbab2df9baee953a

