groups:
  - name: payments-slo-burn
    interval: 1m
    rules:
      - alert: PaymentsAvailabilityErrorBudgetBurnPage
        expr: |
          (
            sum(rate(http_requests_total{service="payments",environment="production",status=~"5..|429"}[5m]))
            /
            sum(rate(http_requests_total{service="payments",environment="production"}[5m]))
          ) > (1 - 0.999) * 14.4
          and
          (
            sum(rate(http_requests_total{service="payments",environment="production",status=~"5..|429"}[1h]))
            /
            sum(rate(http_requests_total{service="payments",environment="production"}[1h]))
          ) > (1 - 0.999) * 6
        for: 5m
        labels:
          severity: critical
          service: payments
          owner: team-payments
          environment: production
          Critical: "0"
        annotations:
          summary: "Payments availability SLO fast burn (page)"
          description: "Error budget burning fast across 5m and 1h windows (>14.4x & >6x). Target 99.9%/30d."
          runbook_url: "docs/runbooks/payments-error-burst.md"
          slo_target: "99.9%"
          slo_window: "30d"
          dashboard: "observability/dashboards/service_overview.json"

      - alert: PaymentsAvailabilityErrorBudgetBurnWarn
        expr: |
          (
            sum(rate(http_requests_total{service="payments",environment="production",status=~"5..|429"}[30m]))
            /
            sum(rate(http_requests_total{service="payments",environment="production"}[30m]))
          ) > (1 - 0.999) * 3
          and
          (
            sum(rate(http_requests_total{service="payments",environment="production",status=~"5..|429"}[6h]))
            /
            sum(rate(http_requests_total{service="payments",environment="production"}[6h]))
          ) > (1 - 0.999) * 1
        for: 15m
        labels:
          severity: warning
          service: payments
          owner: team-payments
          environment: production
          Critical: "0"
        annotations:
          summary: "Payments availability SLO slow burn (warn)"
          description: "Error budget burning over 30m and 6h windows (>3x & >1x). Target 99.9%/30d."
          runbook_url: "docs/runbooks/payments-error-burst.md"
          slo_target: "99.9%"
          slo_window: "30d"
          dashboard: "observability/dashboards/service_overview.json"

