apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-staging
resources:
  - ../../base
  - namespace.yaml
patches:
  - target:
      kind: Rollout
      name: app-rollout
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
images:
  - name: ghcr.io/placeholder/app
    newName: ghcr.io/${REPO}
    newTag: ${APP_IMAGE_SHA}

