name: QA Framework

on:
  pull_request:
    paths:
      - 'frameworks/qa-test/**'
      - 'frameworks/planning-fe/**'
      - 'frameworks/planning-be/**'
  push:
    branches: [ main ]
    paths:
      - 'frameworks/qa-test/**'

jobs:
  gates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema pyyaml
      - name: Run gates and seal (dry-run)
        run: |
          python frameworks/qa-test/cli/qa_framework.py gates --cycle 2025-09